// Autogenerated from Pigeon (v24.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.nottik.app.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeNotificationRecord (
  val id: Long? = null,
  val notificationKey: String? = null,
  val packageName: String? = null,
  val appName: String? = null,
  val notificationId: Long? = null,
  val tag: String? = null,
  val postTime: Long? = null,
  val firstCapturedTime: Long? = null,
  val lastUpdateTime: Long? = null,
  val groupKey: String? = null,
  val channelId: String? = null,
  val priority: Long? = null,
  val visibility: Long? = null,
  val isOngoing: Boolean? = null,
  val isClearable: Boolean? = null,
  val isGroupSummary: Boolean? = null,
  val isRemoved: Boolean? = null,
  val removalReason: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeNotificationRecord {
      val id = pigeonVar_list[0] as Long?
      val notificationKey = pigeonVar_list[1] as String?
      val packageName = pigeonVar_list[2] as String?
      val appName = pigeonVar_list[3] as String?
      val notificationId = pigeonVar_list[4] as Long?
      val tag = pigeonVar_list[5] as String?
      val postTime = pigeonVar_list[6] as Long?
      val firstCapturedTime = pigeonVar_list[7] as Long?
      val lastUpdateTime = pigeonVar_list[8] as Long?
      val groupKey = pigeonVar_list[9] as String?
      val channelId = pigeonVar_list[10] as String?
      val priority = pigeonVar_list[11] as Long?
      val visibility = pigeonVar_list[12] as Long?
      val isOngoing = pigeonVar_list[13] as Boolean?
      val isClearable = pigeonVar_list[14] as Boolean?
      val isGroupSummary = pigeonVar_list[15] as Boolean?
      val isRemoved = pigeonVar_list[16] as Boolean?
      val removalReason = pigeonVar_list[17] as Long?
      return NativeNotificationRecord(id, notificationKey, packageName, appName, notificationId, tag, postTime, firstCapturedTime, lastUpdateTime, groupKey, channelId, priority, visibility, isOngoing, isClearable, isGroupSummary, isRemoved, removalReason)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      notificationKey,
      packageName,
      appName,
      notificationId,
      tag,
      postTime,
      firstCapturedTime,
      lastUpdateTime,
      groupKey,
      channelId,
      priority,
      visibility,
      isOngoing,
      isClearable,
      isGroupSummary,
      isRemoved,
      removalReason,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeNotificationRevision (
  val id: Long? = null,
  val parentRecordId: Long? = null,
  val captureTimestamp: Long? = null,
  val contentHash: String? = null,
  val title: String? = null,
  val text: String? = null,
  val subText: String? = null,
  val bigText: String? = null,
  val summaryText: String? = null,
  val infoText: String? = null,
  val conversationTitle: String? = null,
  val progressMax: Long? = null,
  val progressValue: Long? = null,
  val progressIndeterminate: Boolean? = null,
  val category: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeNotificationRevision {
      val id = pigeonVar_list[0] as Long?
      val parentRecordId = pigeonVar_list[1] as Long?
      val captureTimestamp = pigeonVar_list[2] as Long?
      val contentHash = pigeonVar_list[3] as String?
      val title = pigeonVar_list[4] as String?
      val text = pigeonVar_list[5] as String?
      val subText = pigeonVar_list[6] as String?
      val bigText = pigeonVar_list[7] as String?
      val summaryText = pigeonVar_list[8] as String?
      val infoText = pigeonVar_list[9] as String?
      val conversationTitle = pigeonVar_list[10] as String?
      val progressMax = pigeonVar_list[11] as Long?
      val progressValue = pigeonVar_list[12] as Long?
      val progressIndeterminate = pigeonVar_list[13] as Boolean?
      val category = pigeonVar_list[14] as String?
      return NativeNotificationRevision(id, parentRecordId, captureTimestamp, contentHash, title, text, subText, bigText, summaryText, infoText, conversationTitle, progressMax, progressValue, progressIndeterminate, category)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      parentRecordId,
      captureTimestamp,
      contentHash,
      title,
      text,
      subText,
      bigText,
      summaryText,
      infoText,
      conversationTitle,
      progressMax,
      progressValue,
      progressIndeterminate,
      category,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PaginatedResult (
  val items: List<NativeNotificationRecord?>? = null,
  val hasMore: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PaginatedResult {
      val items = pigeonVar_list[0] as List<NativeNotificationRecord?>?
      val hasMore = pigeonVar_list[1] as Boolean?
      return PaginatedResult(items, hasMore)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      items,
      hasMore,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAppMetadata (
  val packageName: String? = null,
  val appName: String? = null,
  val isLoggingEnabled: Boolean? = null,
  val retentionDays: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAppMetadata {
      val packageName = pigeonVar_list[0] as String?
      val appName = pigeonVar_list[1] as String?
      val isLoggingEnabled = pigeonVar_list[2] as Boolean?
      val retentionDays = pigeonVar_list[3] as Long?
      return NativeAppMetadata(packageName, appName, isLoggingEnabled, retentionDays)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packageName,
      appName,
      isLoggingEnabled,
      retentionDays,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ListenerDiagnostics (
  val isRunning: Boolean? = null,
  val hasError: Boolean? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ListenerDiagnostics {
      val isRunning = pigeonVar_list[0] as Boolean?
      val hasError = pigeonVar_list[1] as Boolean?
      val errorMessage = pigeonVar_list[2] as String?
      return ListenerDiagnostics(isRunning, hasError, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isRunning,
      hasError,
      errorMessage,
    )
  }
}
private open class PigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeNotificationRecord.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeNotificationRevision.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PaginatedResult.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAppMetadata.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ListenerDiagnostics.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeNotificationRecord -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NativeNotificationRevision -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PaginatedResult -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NativeAppMetadata -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ListenerDiagnostics -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NotificationBridge {
  fun isListenerConnected(): Boolean
  fun openListenerSettings()
  fun requestRebind()
  fun getListenerDiagnostics(callback: (Result<ListenerDiagnostics>) -> Unit)
  fun getLatestHistory(offset: Long, limit: Long, searchQuery: String?, category: String?, callback: (Result<PaginatedResult>) -> Unit)
  fun getRecordDetails(id: Long, callback: (Result<NativeNotificationRecord?>) -> Unit)
  fun getRevisions(recordId: Long, callback: (Result<List<NativeNotificationRevision?>>) -> Unit)
  fun getAllAppMetadata(callback: (Result<List<NativeAppMetadata?>>) -> Unit)
  fun getAppMetadata(packageName: String, callback: (Result<NativeAppMetadata?>) -> Unit)
  fun setAppLoggingStatus(packageName: String, enabled: Boolean, callback: (Result<Unit>) -> Unit)
  fun exportData(type: String, callback: (Result<Unit>) -> Unit)
  fun getNativeLogFiles(): List<String>

  companion object {
    /** The codec used by NotificationBridge. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonPigeonCodec()
    }
    /** Sets up an instance of `NotificationBridge` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NotificationBridge?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.isListenerConnected$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isListenerConnected())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.openListenerSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openListenerSettings()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.requestRebind$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestRebind()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.getListenerDiagnostics$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getListenerDiagnostics{ result: Result<ListenerDiagnostics> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.getLatestHistory$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val offsetArg = args[0] as Long
            val limitArg = args[1] as Long
            val searchQueryArg = args[2] as String?
            val categoryArg = args[3] as String?
            api.getLatestHistory(offsetArg, limitArg, searchQueryArg, categoryArg) { result: Result<PaginatedResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.getRecordDetails$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            api.getRecordDetails(idArg) { result: Result<NativeNotificationRecord?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.getRevisions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordIdArg = args[0] as Long
            api.getRevisions(recordIdArg) { result: Result<List<NativeNotificationRevision?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.getAllAppMetadata$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getAllAppMetadata{ result: Result<List<NativeAppMetadata?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.getAppMetadata$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            api.getAppMetadata(packageNameArg) { result: Result<NativeAppMetadata?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.setAppLoggingStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val enabledArg = args[1] as Boolean
            api.setAppLoggingStatus(packageNameArg, enabledArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.exportData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as String
            api.exportData(typeArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.getNativeLogFiles$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getNativeLogFiles())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
