// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.nottik.app.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PigeonPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeNotificationRecord (
  val id: Long? = null,
  val notificationKey: String? = null,
  val packageName: String? = null,
  val appName: String? = null,
  val notificationId: Long? = null,
  val tag: String? = null,
  val postTime: Long? = null,
  val firstCapturedTime: Long? = null,
  val lastUpdateTime: Long? = null,
  val groupKey: String? = null,
  val channelId: String? = null,
  val priority: Long? = null,
  val visibility: Long? = null,
  val isOngoing: Boolean? = null,
  val isClearable: Boolean? = null,
  val isGroupSummary: Boolean? = null,
  val isRemoved: Boolean? = null,
  val removalReason: Long? = null,
  val senderName: String? = null,
  /** Latest revision title for list preview. */
  val latestTitle: String? = null,
  /** Latest revision body for list preview. */
  val latestText: String? = null,
  /** Absolute path to cached app icon (local file). */
  val appIconPath: String? = null,
  /** Absolute path to latest captured media (big picture / messaging image / large icon). */
  val mediaPath: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeNotificationRecord {
      val id = pigeonVar_list[0] as Long?
      val notificationKey = pigeonVar_list[1] as String?
      val packageName = pigeonVar_list[2] as String?
      val appName = pigeonVar_list[3] as String?
      val notificationId = pigeonVar_list[4] as Long?
      val tag = pigeonVar_list[5] as String?
      val postTime = pigeonVar_list[6] as Long?
      val firstCapturedTime = pigeonVar_list[7] as Long?
      val lastUpdateTime = pigeonVar_list[8] as Long?
      val groupKey = pigeonVar_list[9] as String?
      val channelId = pigeonVar_list[10] as String?
      val priority = pigeonVar_list[11] as Long?
      val visibility = pigeonVar_list[12] as Long?
      val isOngoing = pigeonVar_list[13] as Boolean?
      val isClearable = pigeonVar_list[14] as Boolean?
      val isGroupSummary = pigeonVar_list[15] as Boolean?
      val isRemoved = pigeonVar_list[16] as Boolean?
      val removalReason = pigeonVar_list[17] as Long?
      val senderName = pigeonVar_list[18] as String?
      val latestTitle = pigeonVar_list[19] as String?
      val latestText = pigeonVar_list[20] as String?
      val appIconPath = pigeonVar_list[21] as String?
      val mediaPath = pigeonVar_list[22] as String?
      return NativeNotificationRecord(id, notificationKey, packageName, appName, notificationId, tag, postTime, firstCapturedTime, lastUpdateTime, groupKey, channelId, priority, visibility, isOngoing, isClearable, isGroupSummary, isRemoved, removalReason, senderName, latestTitle, latestText, appIconPath, mediaPath)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      notificationKey,
      packageName,
      appName,
      notificationId,
      tag,
      postTime,
      firstCapturedTime,
      lastUpdateTime,
      groupKey,
      channelId,
      priority,
      visibility,
      isOngoing,
      isClearable,
      isGroupSummary,
      isRemoved,
      removalReason,
      senderName,
      latestTitle,
      latestText,
      appIconPath,
      mediaPath,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeNotificationRecord
    return PigeonPigeonUtils.deepEquals(this.id, other.id) && PigeonPigeonUtils.deepEquals(this.notificationKey, other.notificationKey) && PigeonPigeonUtils.deepEquals(this.packageName, other.packageName) && PigeonPigeonUtils.deepEquals(this.appName, other.appName) && PigeonPigeonUtils.deepEquals(this.notificationId, other.notificationId) && PigeonPigeonUtils.deepEquals(this.tag, other.tag) && PigeonPigeonUtils.deepEquals(this.postTime, other.postTime) && PigeonPigeonUtils.deepEquals(this.firstCapturedTime, other.firstCapturedTime) && PigeonPigeonUtils.deepEquals(this.lastUpdateTime, other.lastUpdateTime) && PigeonPigeonUtils.deepEquals(this.groupKey, other.groupKey) && PigeonPigeonUtils.deepEquals(this.channelId, other.channelId) && PigeonPigeonUtils.deepEquals(this.priority, other.priority) && PigeonPigeonUtils.deepEquals(this.visibility, other.visibility) && PigeonPigeonUtils.deepEquals(this.isOngoing, other.isOngoing) && PigeonPigeonUtils.deepEquals(this.isClearable, other.isClearable) && PigeonPigeonUtils.deepEquals(this.isGroupSummary, other.isGroupSummary) && PigeonPigeonUtils.deepEquals(this.isRemoved, other.isRemoved) && PigeonPigeonUtils.deepEquals(this.removalReason, other.removalReason) && PigeonPigeonUtils.deepEquals(this.senderName, other.senderName) && PigeonPigeonUtils.deepEquals(this.latestTitle, other.latestTitle) && PigeonPigeonUtils.deepEquals(this.latestText, other.latestText) && PigeonPigeonUtils.deepEquals(this.appIconPath, other.appIconPath) && PigeonPigeonUtils.deepEquals(this.mediaPath, other.mediaPath)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonPigeonUtils.deepHash(this.id)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.notificationKey)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.packageName)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.appName)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.notificationId)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.tag)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.postTime)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.firstCapturedTime)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.lastUpdateTime)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.groupKey)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.channelId)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.priority)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.visibility)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.isOngoing)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.isClearable)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.isGroupSummary)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.isRemoved)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.removalReason)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.senderName)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.latestTitle)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.latestText)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.appIconPath)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.mediaPath)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeNotificationRevision (
  val id: Long? = null,
  val parentRecordId: Long? = null,
  val captureTimestamp: Long? = null,
  val contentHash: String? = null,
  val title: String? = null,
  val text: String? = null,
  val subText: String? = null,
  val bigText: String? = null,
  val summaryText: String? = null,
  val infoText: String? = null,
  val conversationTitle: String? = null,
  val progressMax: Long? = null,
  val progressValue: Long? = null,
  val progressIndeterminate: Boolean? = null,
  val category: String? = null,
  val mediaPath: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeNotificationRevision {
      val id = pigeonVar_list[0] as Long?
      val parentRecordId = pigeonVar_list[1] as Long?
      val captureTimestamp = pigeonVar_list[2] as Long?
      val contentHash = pigeonVar_list[3] as String?
      val title = pigeonVar_list[4] as String?
      val text = pigeonVar_list[5] as String?
      val subText = pigeonVar_list[6] as String?
      val bigText = pigeonVar_list[7] as String?
      val summaryText = pigeonVar_list[8] as String?
      val infoText = pigeonVar_list[9] as String?
      val conversationTitle = pigeonVar_list[10] as String?
      val progressMax = pigeonVar_list[11] as Long?
      val progressValue = pigeonVar_list[12] as Long?
      val progressIndeterminate = pigeonVar_list[13] as Boolean?
      val category = pigeonVar_list[14] as String?
      val mediaPath = pigeonVar_list[15] as String?
      return NativeNotificationRevision(id, parentRecordId, captureTimestamp, contentHash, title, text, subText, bigText, summaryText, infoText, conversationTitle, progressMax, progressValue, progressIndeterminate, category, mediaPath)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      parentRecordId,
      captureTimestamp,
      contentHash,
      title,
      text,
      subText,
      bigText,
      summaryText,
      infoText,
      conversationTitle,
      progressMax,
      progressValue,
      progressIndeterminate,
      category,
      mediaPath,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeNotificationRevision
    return PigeonPigeonUtils.deepEquals(this.id, other.id) && PigeonPigeonUtils.deepEquals(this.parentRecordId, other.parentRecordId) && PigeonPigeonUtils.deepEquals(this.captureTimestamp, other.captureTimestamp) && PigeonPigeonUtils.deepEquals(this.contentHash, other.contentHash) && PigeonPigeonUtils.deepEquals(this.title, other.title) && PigeonPigeonUtils.deepEquals(this.text, other.text) && PigeonPigeonUtils.deepEquals(this.subText, other.subText) && PigeonPigeonUtils.deepEquals(this.bigText, other.bigText) && PigeonPigeonUtils.deepEquals(this.summaryText, other.summaryText) && PigeonPigeonUtils.deepEquals(this.infoText, other.infoText) && PigeonPigeonUtils.deepEquals(this.conversationTitle, other.conversationTitle) && PigeonPigeonUtils.deepEquals(this.progressMax, other.progressMax) && PigeonPigeonUtils.deepEquals(this.progressValue, other.progressValue) && PigeonPigeonUtils.deepEquals(this.progressIndeterminate, other.progressIndeterminate) && PigeonPigeonUtils.deepEquals(this.category, other.category) && PigeonPigeonUtils.deepEquals(this.mediaPath, other.mediaPath)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonPigeonUtils.deepHash(this.id)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.parentRecordId)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.captureTimestamp)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.contentHash)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.title)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.text)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.subText)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.bigText)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.summaryText)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.infoText)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.conversationTitle)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.progressMax)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.progressValue)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.progressIndeterminate)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.category)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.mediaPath)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PaginatedResult (
  val items: List<NativeNotificationRecord?>? = null,
  val hasMore: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PaginatedResult {
      val items = pigeonVar_list[0] as List<NativeNotificationRecord?>?
      val hasMore = pigeonVar_list[1] as Boolean?
      return PaginatedResult(items, hasMore)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      items,
      hasMore,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PaginatedResult
    return PigeonPigeonUtils.deepEquals(this.items, other.items) && PigeonPigeonUtils.deepEquals(this.hasMore, other.hasMore)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonPigeonUtils.deepHash(this.items)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.hasMore)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAppMetadata (
  val packageName: String? = null,
  val appName: String? = null,
  val isLoggingEnabled: Boolean? = null,
  val retentionDays: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAppMetadata {
      val packageName = pigeonVar_list[0] as String?
      val appName = pigeonVar_list[1] as String?
      val isLoggingEnabled = pigeonVar_list[2] as Boolean?
      val retentionDays = pigeonVar_list[3] as Long?
      return NativeAppMetadata(packageName, appName, isLoggingEnabled, retentionDays)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packageName,
      appName,
      isLoggingEnabled,
      retentionDays,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAppMetadata
    return PigeonPigeonUtils.deepEquals(this.packageName, other.packageName) && PigeonPigeonUtils.deepEquals(this.appName, other.appName) && PigeonPigeonUtils.deepEquals(this.isLoggingEnabled, other.isLoggingEnabled) && PigeonPigeonUtils.deepEquals(this.retentionDays, other.retentionDays)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonPigeonUtils.deepHash(this.packageName)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.appName)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.isLoggingEnabled)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.retentionDays)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ListenerDiagnostics (
  val isRunning: Boolean? = null,
  val hasError: Boolean? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ListenerDiagnostics {
      val isRunning = pigeonVar_list[0] as Boolean?
      val hasError = pigeonVar_list[1] as Boolean?
      val errorMessage = pigeonVar_list[2] as String?
      return ListenerDiagnostics(isRunning, hasError, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isRunning,
      hasError,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ListenerDiagnostics
    return PigeonPigeonUtils.deepEquals(this.isRunning, other.isRunning) && PigeonPigeonUtils.deepEquals(this.hasError, other.hasError) && PigeonPigeonUtils.deepEquals(this.errorMessage, other.errorMessage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonPigeonUtils.deepHash(this.isRunning)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.hasError)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.errorMessage)
    return result
  }
}
private open class PigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeNotificationRecord.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeNotificationRevision.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PaginatedResult.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAppMetadata.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ListenerDiagnostics.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeNotificationRecord -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NativeNotificationRevision -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PaginatedResult -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NativeAppMetadata -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ListenerDiagnostics -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NotificationBridge {
  fun isListenerConnected(): Boolean
  fun openListenerSettings()
  fun requestRebind()
  fun getListenerDiagnostics(callback: (Result<ListenerDiagnostics>) -> Unit)
  fun getLatestHistory(offset: Long, limit: Long, searchQuery: String?, category: String?, callback: (Result<PaginatedResult>) -> Unit)
  fun getRecordDetails(id: Long, callback: (Result<NativeNotificationRecord?>) -> Unit)
  fun getRevisions(recordId: Long, callback: (Result<List<NativeNotificationRevision?>>) -> Unit)
  fun getAllAppMetadata(callback: (Result<List<NativeAppMetadata?>>) -> Unit)
  fun getAppMetadata(packageName: String, callback: (Result<NativeAppMetadata?>) -> Unit)
  fun setAppLoggingStatus(packageName: String, enabled: Boolean, callback: (Result<Unit>) -> Unit)
  fun exportData(type: String, callback: (Result<Unit>) -> Unit)
  fun getNativeLogFiles(): List<String>

  companion object {
    /** The codec used by NotificationBridge. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonPigeonCodec()
    }
    /** Sets up an instance of `NotificationBridge` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NotificationBridge?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.isListenerConnected$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isListenerConnected())
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.openListenerSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openListenerSettings()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.requestRebind$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestRebind()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.getListenerDiagnostics$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getListenerDiagnostics{ result: Result<ListenerDiagnostics> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.getLatestHistory$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val offsetArg = args[0] as Long
            val limitArg = args[1] as Long
            val searchQueryArg = args[2] as String?
            val categoryArg = args[3] as String?
            api.getLatestHistory(offsetArg, limitArg, searchQueryArg, categoryArg) { result: Result<PaginatedResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.getRecordDetails$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            api.getRecordDetails(idArg) { result: Result<NativeNotificationRecord?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.getRevisions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordIdArg = args[0] as Long
            api.getRevisions(recordIdArg) { result: Result<List<NativeNotificationRevision?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.getAllAppMetadata$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getAllAppMetadata{ result: Result<List<NativeAppMetadata?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.getAppMetadata$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            api.getAppMetadata(packageNameArg) { result: Result<NativeAppMetadata?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.setAppLoggingStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val enabledArg = args[1] as Boolean
            api.setAppLoggingStatus(packageNameArg, enabledArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                reply.reply(PigeonPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.exportData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as String
            api.exportData(typeArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                reply.reply(PigeonPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nottik.NotificationBridge.getNativeLogFiles$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getNativeLogFiles())
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
