// Autogenerated from Pigeon (v24.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

class NativeNotificationRecord {
  NativeNotificationRecord({
    this.id,
    this.notificationKey,
    this.packageName,
    this.appName,
    this.notificationId,
    this.tag,
    this.postTime,
    this.firstCapturedTime,
    this.lastUpdateTime,
    this.groupKey,
    this.channelId,
    this.priority,
    this.visibility,
    this.isOngoing,
    this.isClearable,
    this.isGroupSummary,
    this.isRemoved,
    this.removalReason,
  });

  int? id;

  String? notificationKey;

  String? packageName;

  String? appName;

  int? notificationId;

  String? tag;

  int? postTime;

  int? firstCapturedTime;

  int? lastUpdateTime;

  String? groupKey;

  String? channelId;

  int? priority;

  int? visibility;

  bool? isOngoing;

  bool? isClearable;

  bool? isGroupSummary;

  bool? isRemoved;

  int? removalReason;

  Object encode() {
    return <Object?>[
      id,
      notificationKey,
      packageName,
      appName,
      notificationId,
      tag,
      postTime,
      firstCapturedTime,
      lastUpdateTime,
      groupKey,
      channelId,
      priority,
      visibility,
      isOngoing,
      isClearable,
      isGroupSummary,
      isRemoved,
      removalReason,
    ];
  }

  static NativeNotificationRecord decode(Object result) {
    result as List<Object?>;
    return NativeNotificationRecord(
      id: result[0] as int?,
      notificationKey: result[1] as String?,
      packageName: result[2] as String?,
      appName: result[3] as String?,
      notificationId: result[4] as int?,
      tag: result[5] as String?,
      postTime: result[6] as int?,
      firstCapturedTime: result[7] as int?,
      lastUpdateTime: result[8] as int?,
      groupKey: result[9] as String?,
      channelId: result[10] as String?,
      priority: result[11] as int?,
      visibility: result[12] as int?,
      isOngoing: result[13] as bool?,
      isClearable: result[14] as bool?,
      isGroupSummary: result[15] as bool?,
      isRemoved: result[16] as bool?,
      removalReason: result[17] as int?,
    );
  }
}

class NativeNotificationRevision {
  NativeNotificationRevision({
    this.id,
    this.parentRecordId,
    this.captureTimestamp,
    this.contentHash,
    this.title,
    this.text,
    this.subText,
    this.bigText,
    this.summaryText,
    this.infoText,
    this.conversationTitle,
    this.progressMax,
    this.progressValue,
    this.progressIndeterminate,
    this.category,
  });

  int? id;

  int? parentRecordId;

  int? captureTimestamp;

  String? contentHash;

  String? title;

  String? text;

  String? subText;

  String? bigText;

  String? summaryText;

  String? infoText;

  String? conversationTitle;

  int? progressMax;

  int? progressValue;

  bool? progressIndeterminate;

  String? category;

  Object encode() {
    return <Object?>[
      id,
      parentRecordId,
      captureTimestamp,
      contentHash,
      title,
      text,
      subText,
      bigText,
      summaryText,
      infoText,
      conversationTitle,
      progressMax,
      progressValue,
      progressIndeterminate,
      category,
    ];
  }

  static NativeNotificationRevision decode(Object result) {
    result as List<Object?>;
    return NativeNotificationRevision(
      id: result[0] as int?,
      parentRecordId: result[1] as int?,
      captureTimestamp: result[2] as int?,
      contentHash: result[3] as String?,
      title: result[4] as String?,
      text: result[5] as String?,
      subText: result[6] as String?,
      bigText: result[7] as String?,
      summaryText: result[8] as String?,
      infoText: result[9] as String?,
      conversationTitle: result[10] as String?,
      progressMax: result[11] as int?,
      progressValue: result[12] as int?,
      progressIndeterminate: result[13] as bool?,
      category: result[14] as String?,
    );
  }
}

class PaginatedResult {
  PaginatedResult({
    this.items,
    this.hasMore,
  });

  List<NativeNotificationRecord?>? items;

  bool? hasMore;

  Object encode() {
    return <Object?>[
      items,
      hasMore,
    ];
  }

  static PaginatedResult decode(Object result) {
    result as List<Object?>;
    return PaginatedResult(
      items: (result[0] as List<Object?>?)?.cast<NativeNotificationRecord?>(),
      hasMore: result[1] as bool?,
    );
  }
}

class NativeAppMetadata {
  NativeAppMetadata({
    this.packageName,
    this.appName,
    this.isLoggingEnabled,
    this.retentionDays,
  });

  String? packageName;

  String? appName;

  bool? isLoggingEnabled;

  int? retentionDays;

  Object encode() {
    return <Object?>[
      packageName,
      appName,
      isLoggingEnabled,
      retentionDays,
    ];
  }

  static NativeAppMetadata decode(Object result) {
    result as List<Object?>;
    return NativeAppMetadata(
      packageName: result[0] as String?,
      appName: result[1] as String?,
      isLoggingEnabled: result[2] as bool?,
      retentionDays: result[3] as int?,
    );
  }
}

class ListenerDiagnostics {
  ListenerDiagnostics({
    this.isRunning,
    this.hasError,
    this.errorMessage,
  });

  bool? isRunning;

  bool? hasError;

  String? errorMessage;

  Object encode() {
    return <Object?>[
      isRunning,
      hasError,
      errorMessage,
    ];
  }

  static ListenerDiagnostics decode(Object result) {
    result as List<Object?>;
    return ListenerDiagnostics(
      isRunning: result[0] as bool?,
      hasError: result[1] as bool?,
      errorMessage: result[2] as String?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NativeNotificationRecord) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is NativeNotificationRevision) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is PaginatedResult) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is NativeAppMetadata) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is ListenerDiagnostics) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return NativeNotificationRecord.decode(readValue(buffer)!);
      case 130: 
        return NativeNotificationRevision.decode(readValue(buffer)!);
      case 131: 
        return PaginatedResult.decode(readValue(buffer)!);
      case 132: 
        return NativeAppMetadata.decode(readValue(buffer)!);
      case 133: 
        return ListenerDiagnostics.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class NotificationBridge {
  /// Constructor for [NotificationBridge].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NotificationBridge({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> isListenerConnected() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.isListenerConnected$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<void> openListenerSettings() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.openListenerSettings$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> requestRebind() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.requestRebind$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<ListenerDiagnostics> getListenerDiagnostics() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.getListenerDiagnostics$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as ListenerDiagnostics?)!;
    }
  }

  Future<PaginatedResult> getLatestHistory(int offset, int limit, String? searchQuery, String? category) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.getLatestHistory$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[offset, limit, searchQuery, category]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PaginatedResult?)!;
    }
  }

  Future<NativeNotificationRecord?> getRecordDetails(int id) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.getRecordDetails$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as NativeNotificationRecord?);
    }
  }

  Future<List<NativeNotificationRevision?>> getRevisions(int recordId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.getRevisions$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[recordId]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<NativeNotificationRevision?>();
    }
  }

  Future<List<NativeAppMetadata?>> getAllAppMetadata() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.getAllAppMetadata$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<NativeAppMetadata?>();
    }
  }

  Future<NativeAppMetadata?> getAppMetadata(String packageName) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.getAppMetadata$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[packageName]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as NativeAppMetadata?);
    }
  }

  Future<void> setAppLoggingStatus(String packageName, bool enabled) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.setAppLoggingStatus$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[packageName, enabled]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> exportData(String type) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.exportData$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[type]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<List<String>> getNativeLogFiles() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.getNativeLogFiles$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<String>();
    }
  }
}
