// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


class NativeNotificationRecord {
  NativeNotificationRecord({
    this.id,
    this.notificationKey,
    this.packageName,
    this.appName,
    this.notificationId,
    this.tag,
    this.postTime,
    this.firstCapturedTime,
    this.lastUpdateTime,
    this.groupKey,
    this.channelId,
    this.priority,
    this.visibility,
    this.isOngoing,
    this.isClearable,
    this.isGroupSummary,
    this.isRemoved,
    this.removalReason,
    this.senderName,
  });

  int? id;

  String? notificationKey;

  String? packageName;

  String? appName;

  int? notificationId;

  String? tag;

  int? postTime;

  int? firstCapturedTime;

  int? lastUpdateTime;

  String? groupKey;

  String? channelId;

  int? priority;

  int? visibility;

  bool? isOngoing;

  bool? isClearable;

  bool? isGroupSummary;

  bool? isRemoved;

  int? removalReason;

  String? senderName;

  List<Object?> _toList() {
    return <Object?>[
      id,
      notificationKey,
      packageName,
      appName,
      notificationId,
      tag,
      postTime,
      firstCapturedTime,
      lastUpdateTime,
      groupKey,
      channelId,
      priority,
      visibility,
      isOngoing,
      isClearable,
      isGroupSummary,
      isRemoved,
      removalReason,
      senderName,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeNotificationRecord decode(Object result) {
    result as List<Object?>;
    return NativeNotificationRecord(
      id: result[0] as int?,
      notificationKey: result[1] as String?,
      packageName: result[2] as String?,
      appName: result[3] as String?,
      notificationId: result[4] as int?,
      tag: result[5] as String?,
      postTime: result[6] as int?,
      firstCapturedTime: result[7] as int?,
      lastUpdateTime: result[8] as int?,
      groupKey: result[9] as String?,
      channelId: result[10] as String?,
      priority: result[11] as int?,
      visibility: result[12] as int?,
      isOngoing: result[13] as bool?,
      isClearable: result[14] as bool?,
      isGroupSummary: result[15] as bool?,
      isRemoved: result[16] as bool?,
      removalReason: result[17] as int?,
      senderName: result[18] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeNotificationRecord || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(notificationKey, other.notificationKey) && _deepEquals(packageName, other.packageName) && _deepEquals(appName, other.appName) && _deepEquals(notificationId, other.notificationId) && _deepEquals(tag, other.tag) && _deepEquals(postTime, other.postTime) && _deepEquals(firstCapturedTime, other.firstCapturedTime) && _deepEquals(lastUpdateTime, other.lastUpdateTime) && _deepEquals(groupKey, other.groupKey) && _deepEquals(channelId, other.channelId) && _deepEquals(priority, other.priority) && _deepEquals(visibility, other.visibility) && _deepEquals(isOngoing, other.isOngoing) && _deepEquals(isClearable, other.isClearable) && _deepEquals(isGroupSummary, other.isGroupSummary) && _deepEquals(isRemoved, other.isRemoved) && _deepEquals(removalReason, other.removalReason) && _deepEquals(senderName, other.senderName);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class NativeNotificationRevision {
  NativeNotificationRevision({
    this.id,
    this.parentRecordId,
    this.captureTimestamp,
    this.contentHash,
    this.title,
    this.text,
    this.subText,
    this.bigText,
    this.summaryText,
    this.infoText,
    this.conversationTitle,
    this.progressMax,
    this.progressValue,
    this.progressIndeterminate,
    this.category,
    this.mediaPath,
  });

  int? id;

  int? parentRecordId;

  int? captureTimestamp;

  String? contentHash;

  String? title;

  String? text;

  String? subText;

  String? bigText;

  String? summaryText;

  String? infoText;

  String? conversationTitle;

  int? progressMax;

  int? progressValue;

  bool? progressIndeterminate;

  String? category;

  String? mediaPath;

  List<Object?> _toList() {
    return <Object?>[
      id,
      parentRecordId,
      captureTimestamp,
      contentHash,
      title,
      text,
      subText,
      bigText,
      summaryText,
      infoText,
      conversationTitle,
      progressMax,
      progressValue,
      progressIndeterminate,
      category,
      mediaPath,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeNotificationRevision decode(Object result) {
    result as List<Object?>;
    return NativeNotificationRevision(
      id: result[0] as int?,
      parentRecordId: result[1] as int?,
      captureTimestamp: result[2] as int?,
      contentHash: result[3] as String?,
      title: result[4] as String?,
      text: result[5] as String?,
      subText: result[6] as String?,
      bigText: result[7] as String?,
      summaryText: result[8] as String?,
      infoText: result[9] as String?,
      conversationTitle: result[10] as String?,
      progressMax: result[11] as int?,
      progressValue: result[12] as int?,
      progressIndeterminate: result[13] as bool?,
      category: result[14] as String?,
      mediaPath: result[15] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeNotificationRevision || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(parentRecordId, other.parentRecordId) && _deepEquals(captureTimestamp, other.captureTimestamp) && _deepEquals(contentHash, other.contentHash) && _deepEquals(title, other.title) && _deepEquals(text, other.text) && _deepEquals(subText, other.subText) && _deepEquals(bigText, other.bigText) && _deepEquals(summaryText, other.summaryText) && _deepEquals(infoText, other.infoText) && _deepEquals(conversationTitle, other.conversationTitle) && _deepEquals(progressMax, other.progressMax) && _deepEquals(progressValue, other.progressValue) && _deepEquals(progressIndeterminate, other.progressIndeterminate) && _deepEquals(category, other.category) && _deepEquals(mediaPath, other.mediaPath);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class PaginatedResult {
  PaginatedResult({
    this.items,
    this.hasMore,
  });

  List<NativeNotificationRecord?>? items;

  bool? hasMore;

  List<Object?> _toList() {
    return <Object?>[
      items,
      hasMore,
    ];
  }

  Object encode() {
    return _toList();  }

  static PaginatedResult decode(Object result) {
    result as List<Object?>;
    return PaginatedResult(
      items: (result[0] as List<Object?>?)?.cast<NativeNotificationRecord?>(),
      hasMore: result[1] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PaginatedResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(items, other.items) && _deepEquals(hasMore, other.hasMore);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class NativeAppMetadata {
  NativeAppMetadata({
    this.packageName,
    this.appName,
    this.isLoggingEnabled,
    this.retentionDays,
  });

  String? packageName;

  String? appName;

  bool? isLoggingEnabled;

  int? retentionDays;

  List<Object?> _toList() {
    return <Object?>[
      packageName,
      appName,
      isLoggingEnabled,
      retentionDays,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeAppMetadata decode(Object result) {
    result as List<Object?>;
    return NativeAppMetadata(
      packageName: result[0] as String?,
      appName: result[1] as String?,
      isLoggingEnabled: result[2] as bool?,
      retentionDays: result[3] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeAppMetadata || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(packageName, other.packageName) && _deepEquals(appName, other.appName) && _deepEquals(isLoggingEnabled, other.isLoggingEnabled) && _deepEquals(retentionDays, other.retentionDays);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class ListenerDiagnostics {
  ListenerDiagnostics({
    this.isRunning,
    this.hasError,
    this.errorMessage,
  });

  bool? isRunning;

  bool? hasError;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      isRunning,
      hasError,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();  }

  static ListenerDiagnostics decode(Object result) {
    result as List<Object?>;
    return ListenerDiagnostics(
      isRunning: result[0] as bool?,
      hasError: result[1] as bool?,
      errorMessage: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ListenerDiagnostics || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isRunning, other.isRunning) && _deepEquals(hasError, other.hasError) && _deepEquals(errorMessage, other.errorMessage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NativeNotificationRecord) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is NativeNotificationRevision) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is PaginatedResult) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is NativeAppMetadata) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is ListenerDiagnostics) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return NativeNotificationRecord.decode(readValue(buffer)!);
      case 130:
        return NativeNotificationRevision.decode(readValue(buffer)!);
      case 131:
        return PaginatedResult.decode(readValue(buffer)!);
      case 132:
        return NativeAppMetadata.decode(readValue(buffer)!);
      case 133:
        return ListenerDiagnostics.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class NotificationBridge {
  /// Constructor for [NotificationBridge].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NotificationBridge({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> isListenerConnected() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.isListenerConnected$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> openListenerSettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.openListenerSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> requestRebind() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.requestRebind$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<ListenerDiagnostics> getListenerDiagnostics() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.getListenerDiagnostics$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ListenerDiagnostics;
  }

  Future<PaginatedResult> getLatestHistory(int offset, int limit, String? searchQuery, String? category) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.getLatestHistory$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[offset, limit, searchQuery, category]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PaginatedResult;
  }

  Future<NativeNotificationRecord?> getRecordDetails(int id) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.getRecordDetails$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as NativeNotificationRecord?;
  }

  Future<List<NativeNotificationRevision?>> getRevisions(int recordId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.getRevisions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[recordId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<NativeNotificationRevision?>();
  }

  Future<List<NativeAppMetadata?>> getAllAppMetadata() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.getAllAppMetadata$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<NativeAppMetadata?>();
  }

  Future<NativeAppMetadata?> getAppMetadata(String packageName) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.getAppMetadata$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[packageName]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as NativeAppMetadata?;
  }

  Future<void> setAppLoggingStatus(String packageName, bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.setAppLoggingStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[packageName, enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> exportData(String type) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.exportData$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[type]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<List<String>> getNativeLogFiles() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nottik.NotificationBridge.getNativeLogFiles$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }
}
